# Generated by Django 4.1.3 on 2022-11-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
